# Site settings
title: "Ethan's newsletter"
description: > # this means to ignore newlines until "baseurl:"
  What is Ethan doing? What have they been up to? Find out all this and more!
baseurl: "/news" # the subpath of your site, e.g. /blog/
url: "https://funblaster22.github.io" # the base hostname & protocol for your site
github_username:  funblaster22

# Build settings
markdown: kramdown
permalink: /:year/:long_month/index:output_ext
