[package]
name = "news"
version = "0.1.0"
edition = "2021"

[[bin]]
edition = "2021"
name = "server"
path = "server.rs"

[dependencies]
chrono = "0.4.39"
percent-encoding = "2.3.1"
simple_http_parser = "0.3.5"
